// Top-level build file
buildscript {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
    }
}

allprojects {
    repositories {
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
